sudo: required

services:
  - docker

before_install:
  - docker build -t m38io/todomvc .
  - docker run --rm --entrypoint npm m38io/todomvc "test"

notifications:
  email: false

language: node_js
node_js:
  - "5"
  - "5.1"
  - "4"
  - "4.2"
  - "4.1"
  - "4.0"

