sudo: required

services:
  - docker

before_install:
  - docker build -t m38io/todomvc .
  - docker run todomvc /bin/sh -c "cd /usr/src/app; npm test"

script: npm test

language: node_js
node_js:
  - "5"
  - "5.1"
  - "4"
  - "4.2"
  - "4.1"
  - "4.0"

